// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTracker.Infrastructure.Persistence.DataContext;

#nullable disable

namespace TaskTracker.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422172933_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskTracker.Core.Entities.BusinessCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessCategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessCategoryTypeId");

                    b.ToTable("BusinessCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessCategoryTypeId = 1,
                            Description = "Low Priority",
                            IsActive = true,
                            Name = "Low"
                        },
                        new
                        {
                            Id = 2,
                            BusinessCategoryTypeId = 1,
                            Description = "Medium Priority",
                            IsActive = true,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            BusinessCategoryTypeId = 1,
                            Description = "High Priority",
                            IsActive = true,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.BusinessCategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessCategoryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Task Priority Group",
                            IsActive = true,
                            Name = "Priority"
                        });
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubChildId")
                        .HasColumnType("int");

                    b.Property<int?>("SubParentId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 8,
                            IconClass = "nav-icon fa-solid fa-user-shield",
                            IsActive = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Module = "SetUp",
                            Name = "Menu Authorization",
                            ParentId = 0,
                            SubChildId = 0,
                            SubParentId = 0
                        },
                        new
                        {
                            Id = 2,
                            Controller = "MenuAuthorization",
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 9,
                            IconClass = "nav-icon fas fa-user-circle",
                            IsActive = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Module = "SetUp",
                            Name = "Role",
                            ParentId = 1,
                            SubChildId = 0,
                            SubParentId = 0,
                            Url = "/SetUp/MenuAuthorization/Role"
                        },
                        new
                        {
                            Id = 3,
                            Controller = "MenuAuthorization",
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 11,
                            IconClass = "nav-icon fas fa-user-shield",
                            IsActive = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Module = "SetUp",
                            Name = "Role Menu Assign",
                            ParentId = 1,
                            SubChildId = 0,
                            SubParentId = 0,
                            Url = "/SetUp/MenuAuthorization/RoleMenu"
                        },
                        new
                        {
                            Id = 4,
                            Controller = "Task",
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayOrder = 12,
                            IconClass = "nav-icon fas fa-tasks",
                            IsActive = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Module = "SetUp",
                            Name = "Task",
                            ParentId = 1,
                            SubChildId = 0,
                            SubParentId = 0,
                            Url = "/SetUp/Task"
                        });
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("IdentityRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdentityRoleId = new Guid("3cfd9eee-08cb-4da3-9e6f-c3166b50d3b0"),
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdentityRoleId = new Guid("37cc67e1-41ca-461c-bf34-2b5e62dbae32"),
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IdentityRoleId = new Guid("a0cab2c3-6558-4a1c-be81-dfb39180da3d"),
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.RoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("Insert")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("List")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<bool>("Post")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Delete = true,
                            Insert = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            List = true,
                            MenuId = 1,
                            Post = true,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Delete = true,
                            Insert = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            List = true,
                            MenuId = 2,
                            Post = true,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Delete = true,
                            Insert = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            List = true,
                            MenuId = 3,
                            Post = true,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "SYSTEM",
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Delete = true,
                            Insert = true,
                            LastModifiedBy = "SYSTEM",
                            LastModifiedOn = new DateTimeOffset(new DateTime(2024, 11, 18, 10, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            List = true,
                            MenuId = 4,
                            Post = true,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.UserMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool>("Insert")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastUpdateFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("List")
                        .HasColumnType("bit");

                    b.Property<int?>("MenuId")
                        .HasColumnType("int");

                    b.Property<bool>("Post")
                        .HasColumnType("bit");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("UserMenus");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.BusinessCategory", b =>
                {
                    b.HasOne("TaskTracker.Core.Entities.BusinessCategoryType", "BusinessCategoryType")
                        .WithMany("BusinessCategories")
                        .HasForeignKey("BusinessCategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessCategoryType");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.RoleMenu", b =>
                {
                    b.HasOne("TaskTracker.Core.Entities.Menu", "Menu")
                        .WithMany("RoleMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskTracker.Core.Entities.BusinessCategory", "Priority")
                        .WithMany()
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.UserMenu", b =>
                {
                    b.HasOne("TaskTracker.Core.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.BusinessCategoryType", b =>
                {
                    b.Navigation("BusinessCategories");
                });

            modelBuilder.Entity("TaskTracker.Core.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
